services:
  doc:
    image: markdown-to-html
    build:
      context: ./doc/
      dockerfile_inline: |
        FROM node:22-alpine3.19
        RUN npm install -g markdown-folder-to-html
    working_dir: /data
    volumes:
      - ./:/data/
    command: markdown-folder-to-html /data/doc
  kibot:
    image: ghcr.io/inti-cmnb/kicad8_auto:latest # All versions: https://kibot.readthedocs.io/en/master/usage_with_ci_cd.html
    working_dir: /data
    volumes:
      - ./:/data/
    environment:
      # NO_AT_BRIDGE: 1 # Think is not needed
      KICAD_3RD_PARTY: /data/3rdparty/
    command: |
      bash -c "
        CLICOLOR_FORCE=1 kibot 2>&1 | sed 's/WARNING/::warning :/g' | sed 's/ERROR/::error :/g'
      "
  version:
    image: git-and-bash
    build: 
      dockerfile_inline: |
        FROM cicirello/alpine-plus-plus:latest
        RUN git config --global --add safe.directory /data
    working_dir: /data
    volumes:
      - ./:/data/
    command: |
      bash -c '
        set -e -o pipefail 
        VERSIONED_FILES="BatterySwitcher.kicad_pcb BatterySwitcher.kicad_sch"
        if [ -z "$$GIT_VERSION_STRING" ]; then
          echo GIT_VERSION_STRING env variable has not been setted
          exit 1
        fi
        echo Applying version "$$GIT_VERSION_STRING"
        if ! grep "vXX.XX.XXX" $$VERSIONED_FILES > /dev/null; then
          echo "No version string found!"
          exit 1
        fi
        for file in $$VERSIONED_FILES; do
          sed -i "s/vXX.XX.XXX/$$GIT_VERSION_STRING/g" $$file
        done
      '
    environment:
      GIT_VERSION_STRING: ${GIT_VERSION_STRING:-}
