services:
  doc:
    image: markdown-to-html
    build:
      context: ./doc/
      dockerfile_inline: |
        FROM node:22-alpine3.19
        RUN npm install -g markdown-folder-to-html
    working_dir: /data
    volumes:
      - ./:/data/
    command: markdown-folder-to-html /data/doc
  kibot:
    image: ghcr.io/inti-cmnb/kicad8_auto:1.6.5
    working_dir: /data
    volumes:
      - ./:/data/
    environment:
      # NO_AT_BRIDGE: 1 # Think is not needed
      KICAD_3RD_PARTY: /data/3rdparty/
    command: kibot
  version:
    image: git-and-bash
    build: 
      dockerfile_inline: |
        FROM cicirello/alpine-plus-plus:latest
        RUN git config --global --add safe.directory /data
    working_dir: /data
    volumes:
      - ./:/data/
    command: bash -c 'GIT_VERSION_STRING=$(git describe --tags) && sed -i "s/vXX.XX.XX-XXX-XXXXXXXX/$$GIT_VERSION_STRING/g" BatterySwitcher.kicad_pcb'
