name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate user guide and adsd it to the release
        run: docker compose up doc && mv _doc release

      - name: Generate gerbers, schema, images...
        uses: INTI-CMNB/KiBot@v1.7.0
            
      - name: Upload manufacturing files
        uses: actions/upload-artifact@v4.3.3
        with:
          name: manufacturing
          if-no-files-found: error
          path: "Gerbers" 

      - name: Upload release
        uses: actions/upload-artifact@v4.3.3
        with:
          name: release
          if-no-files-found: error
          path: "release/*"
