# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Generate gerber files
      - name: KiBot GitHub action
        uses: INTI-CMNB/KiBot@v1.7.0
            
      - name: Upload manufacturing files
        uses: actions/upload-artifact@v4.3.3
        with:
          name: manufacturing.zip
          if-no-files-found: error
          path: "**.zip" 

      - name: Upload images
        uses: actions/upload-artifact@v4.3.3
        with:
          name: images
          if-no-files-found: error
          path: "**.png" 

      - name: Upload BOM
        uses: actions/upload-artifact@v4.3.3
        with:
          name: BOM
          if-no-files-found: error
          path: "**.html" 

      - name: Upload pdf schematic
        uses: actions/upload-artifact@v4.3.3
        with:
          name: schematic
          if-no-files-found: error
          path: "**.pdf" 

