name: Publish release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} # Branch to merge into main
    steps:

      - uses: actions/checkout@v4

      - uses: ./.github/workflows/release.yml

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: release.yml
          skip_unpack: true

      - name: Inspect project files
        run: ls -lR

      - name: Setup release files
        run: |
          unzip 3d.step.zip
          mv 3d.step 3d-${{ steps.tag.outputs.new_tag }}.zip
          mv manufacturing.zip manufacturing-${{ steps.tag.outputs.new_tag }}.zip
          mv release.zip release-${{ steps.tag.outputs.new_tag }}.zip

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
          artifacts: "3d-${{ steps.tag.outputs.new_tag }}.zip,manufacturing-${{ steps.tag.outputs.new_tag }}.zip,release-${{ steps.tag.outputs.new_tag }}.zip"
