name: release

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: # Needed to get git version
          fetch-depth: 0
          fetch-tags: true

      - name: Generate user guide and adsd it to the release
        run: docker compose up doc && mv _doc release

      - name: Set Git version
        run: docker compose up version

      - name: Generate gerbers, schema, images...
        uses: INTI-CMNB/KiBot@v1.7.0
        env:
          KICAD_3RD_PARTY: ${GITHUB_WORKSPACE}/3rdparty/

      - name: Inspect project files
        run: ls -l . release Gerbers
            
      - name: Upload manufacturing files
        uses: actions/upload-artifact@v4.3.3
        with:
          name: manufacturing
          if-no-files-found: error
          path: "Gerbers" 

      - name: Upload release
        uses: actions/upload-artifact@v4.3.3
        with:
          name: release
          if-no-files-found: error
          path: "release/*"

      - name: Upload 3D
        uses: actions/upload-artifact@v4.3.3
        with:
          name: 3d.step
          if-no-files-found: error
          path: 3d.step
