name: Bump version

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} # Branch to merge into main
    steps:

      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
