name: Bump version

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} # Branch to merge into main
    steps:

      - uses: actions/checkout@v4

      - name: Check release branch
        id: check
        run: |
          if ! [[ "$BRANCH_NAME" =~ release/* ]]; then
            echo "'$BRANCH_NAME' is not a release branch, exiting job"
            echo "donotrelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and push tag
        if : ( steps.check.outputs.donotrelease  != 'true' ) 
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        if : ( steps.check.outputs.donotrelease  != 'true' ) 
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
